GET http://localhost:3000/contacts/319

###
GET http://localhost:3000/contacts

###
POST http://localhost:3000/contacts
content-type: application/json

{
  "first_name": "Smith",
  "last_name": "Smally",
  "email": "ssmalls@smaller.com",
  "phone_number": "555-0123",
  "address": "Hackensack, NJ"
}

###
GET http://localhost:3000/contacts/202/nearest

###
DELETE http://localhost:3000/contacts/319